# Local dev overrides.
# Layer over docker-compose.yml.
services:
  app-backend:
    build:
      context: ..
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_URL: http://localhost:3000
      KEYCLOAK_URL: http://keycloak:8080/keycloak
      KEYCLOAK_REALM: spatialhub
      AUTH_SERVICE_URL: http://auth-service:8001
      WEBSERVICE_SERVICE_URL: http://webservice:8082
